language: node_js
node_js:
  - '10'
install:
  - yarn install
  - yarn build
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip_cleanup: false
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: public
  on:
    branch: master
